[package]
name = "blackjack-engine-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
blackjack-engine = { path = "../blackjack-engine" }
clap = { version = "4.5.27", features = ["derive"] }
ratatui = { version = "0.29.0", features = ["all-widgets"] }
serde_json = "1.0.137"
